### ISSUE TITLE
Which images to use for AP, ML on ICMS probe? Also where is the data for R19-224?

### ISSUE THREAD

**Issue by sdalla** [Cortical-Plasticity-Lab/Solenoid-Ephys-Analyses#13]
Which images do I need to use to get the AP, ML distances for ICMS-Info? 

Where is the data for R19-224 -- i didnt see anything in surgical notes.

**Comment by m053m716** [comment]
@sdalla 
The ICMS-Info AP & ML distances should come from the same images as for recording information, located on the [share drive](https://drive.google.com/drive/u/1/folders/1o0Nm88-Gah89OmnNeeRlKbq9uabfBcEl). If they don't have ICMS sites then it may not have been done for that procedure.

For R19-224, it looks like most likely there wasn't enough time or else ICMS wasn't working properly on that particular procedure. My guess is we didn't have time since it would have been the first one set up in that configuration (cycling through trials). So we would have used stereotaxic centers based on previous literature in combination with the blood vessel patterns. Does R19-224 have any ICMS sites listed in the surgical notes?
